apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: linker-app
  labels:
    app: web-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       
      maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: app-container
        # The tag below is updated by your GitHub Action (sed command)
        image: mrfuntor/devops-bootcamp-linker-frontend-main-backend:${{git.sha}}
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: linker-app-config
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5